### ISSUE TITLE
Description under title

### ISSUE THREAD

**Issue by lfarah** [youkchansim/CSPieChart#1]
<img width="399" alt="screen shot 2017-01-23 at 5 31 28 pm" src="https://cloud.githubusercontent.com/assets/6511079/22219407/cdd27476-e191-11e6-980e-306b4adf3aaf.png">

**Comment by lfarah** [comment]
Please fix this before we can approve [your PR](https://github.com/vsouza/awesome-ios/pull/1418)

**Comment by youkchansim** [comment]
@lfarah hellow . I fixed it :)
