### ISSUE TITLE
cocoapod으로 받은 라이브러리에서 show 삭제 이슈

### ISSUE THREAD

**Issue by gobenpark** [youkchansim/CSPieChart#2]
example코드의 CSPieChart 의 `public extension CSPieChart` 부분의 show 함수 정의부분이 사라졌습니다. 

getotal value부분도 없습니다

**Comment by youkchansim** [comment]
@qkrqjadn 안녕하세요. Pod 버전을 확인부탁드릴게요. 현재 0.5.1버전이며 0.5버전으로 업데이트되며 애니메이션이 추가되어 show 및 getTotalValue가 생성되었습니다.

**Comment by gobenpark** [comment]
어제 코코아팟 확인시 0.4 대 버전이였는데 업데이트가 되었군요 감사합니다 .
