### ISSUE TITLE
pieChartComponentSubView의 서브뷰 

### ISSUE THREAD

**Issue by gobenpark** [youkchansim/CSPieChart#5]
example 의 viewController에서 pieChartComponentSubView  데이터소스코드 부분에서 

기존의 ImageView 부분을 UILabel 교체시 정상적으로 나오지 않는데 레이블 출력 방법이 따로 있는 건가요??

**Comment by youkchansim** [comment]
@qkrqjadn UILabel 출력 하는 예제를 제가 지웠는데요. 버그로 인식하고 UIImageView와 마찬가지로 모든 UIView에서 동작하도록 0.5.2버전에서 수정하였어요. pod 업데이트 후 확인하시고 이슈 처리되었으면 close 부탁드릴게요.

**Comment by gobenpark** [comment]
버전업 하니 잘되네요   감사합니다
